[[redirects]]
  from = "/courses/ict-packages"
  to = "/pages/course-detail.html?course=ict-packages"
  status = 301

[[redirects]]
  from = "/courses/frontend-dev"
  to = "/pages/course-detail.html?course=frontend-dev"
  status = 301

[[redirects]]
  from = "/*"
  to = "/pages/404.html"
  status = 404
